name: "CI Testing for redirect.engr.tamu.edu Rewrite Rules"
on: 
  pull_request:
    branches:
    - staging
    - main
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - '.github/workflows/pull_request.yml' # Changes to only the workflow shouldn't cause tests to run

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: python -m pip install --upgrade pip
    - run: pip install -r ./requirements.txt
    - name: build the SAM rewrite function
      working-directory: ./sam
      run: sam build
    - name: run rewrite tests against rules
      run: python tester/rewrite_tester.py --test_path tests --debug
    - name: Report test results as JUnit tests
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: tests/temp_results/*.xml
        report_individual_runs: "true"